namespace GT2.DataSplitter.GTDT.LicenseData
{
    using Common;
    using Models.Enums;

    public class EventLicense : MappedDataStructure<Event.Data>
    {
        public Models.License.EventLicense MapToModel(ASCIIStringTable strings) =>
            new Models.License.EventLicense
            {
                EventName = strings.Get(data.EventName),
                TrackName = strings.Get(data.TrackName),
                Opponent1 = data.Opponent1,
                Opponent2 = data.Opponent2,
                Opponent3 = data.Opponent3,
                Opponent4 = data.Opponent4,
                Opponent5 = data.Opponent5,
                Opponent6 = data.Opponent6,
                Opponent7 = data.Opponent7,
                Opponent8 = data.Opponent8,
                Opponent9 = data.Opponent9,
                Opponent10 = data.Opponent10,
                Opponent11 = data.Opponent11,
                Opponent12 = data.Opponent12,
                Opponent13 = data.Opponent13,
                Opponent14 = data.Opponent14,
                Opponent15 = data.Opponent15,
                Opponent16 = data.Opponent16,
                RollingStartSpeed = data.RollingStartSpeed,
                Laps = data.Laps,
                AutoDrive = data.AutoDrive,
                Licence = (Licence)data.Licence,
                AIFrontGripRWD = data.AIFrontGripRWD,
                AIFrontGripFWD = data.AIFrontGripFWD,
                AIFrontGrip4WD = data.AIFrontGrip4WD,
                AIFrontGripSpecial4WD = data.AIFrontGripSpecial4WD,
                AIRearGripRWD = data.AIRearGripRWD,
                AIRearGripFWD = data.AIRearGripFWD,
                AIRearGrip4WD = data.AIRearGrip4WD,
                AIRearGripSpecial4WD = data.AIRearGripSpecial4WD,
                AIAccelerationRWD = data.AIAccelerationRWD,
                AIAccelerationFWD = data.AIAccelerationFWD,
                AIAcceleration4WD = data.AIAcceleration4WD,
                AIAccelerationSpecial4WD = data.AIAccelerationSpecial4WD,
                AIThrottleLiftReductionRWD = data.AIThrottleLiftReductionRWD,
                AIThrottleLiftReductionFWD = data.AIThrottleLiftReductionFWD,
                AIThrottleLiftReduction4WD = data.AIThrottleLiftReduction4WD,
                AIThrottleLiftReductionSpecial4WD = data.AIThrottleLiftReductionSpecial4WD,
                AIRubberBandMultiplier = data.AIRubberBandMultiplier,
                AIRubberBandUnknown1 = data.AIRubberBandUnknown1,
                AIRubberBandScaledPerCar = data.AIRubberBandScaledPerCar,
                AIRubberBandLeadingSlowdownPercentage = data.AIRubberBandLeadingSlowdownPercentage,
                AIRubberBandLeadingScalingDistance = data.AIRubberBandLeadingScalingDistance,
                AIRubberBandTrailingSpeedupPercentage = data.AIRubberBandTrailingSpeedupPercentage,
                AIRubberBandTrailingScalingDistance = data.AIRubberBandTrailingScalingDistance,
                TireWearOrangeDurationMultiplier = data.TireWearOrangeDurationMultiplier,
                TireWearOrangeGripLoss = data.TireWearOrangeGripLoss,
                TireWearUnknown = data.TireWearUnknown,
                TireWearBlueDurationMultiplier = data.TireWearBlueDurationMultiplier,
                TireWearBlueGripLoss = data.TireWearBlueGripLoss,
                TireWearGreenDurationMultiplier = data.TireWearGreenDurationMultiplier,
                TireWearGreenGripLoss = data.TireWearGreenGripLoss,
                Unknown1 = data.Unknown1,
                Unknown2 = data.Unknown2,
                Unknown3 = data.Unknown3,
                Unknown4 = data.Unknown4,
                IsRally = data.IsRally == 1,
                EligibleCarsRestriction = data.EligibleCarsRestriction,
                DrivetrainRestriction = (DrivetrainType)data.DrivetrainRestriction,
                PrizeMoney1st = data.PrizeMoney1st,
                PrizeMoney2nd = data.PrizeMoney2nd,
                PrizeMoney3rd = data.PrizeMoney3rd,
                PrizeMoney4th = data.PrizeMoney4th,
                PrizeMoney5th = data.PrizeMoney5th,
                PrizeMoney6th = data.PrizeMoney6th,
                PrizeCars = data.PrizeCars,
                TrackBannerPool = strings.Get(data.TrackBannerPool),
                PSRestriction = data.PSRestriction,
                SeriesChampBonus = data.SeriesChampBonus,
                CarRestrictionFlags = data.CarRestrictionFlags
            };
    }
}